name: swol
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #expand and contract info
  folding_cell: "^0.1.2"

  #ANIMATION
  animator: ^1.0.0+1

  #STATUS AND NAVIGATION BAR
  flutter_statusbarcolor: ^0.2.2

  #AUTO SIZE TEXT
  auto_size_text: ^2.1.0

  #VERTICAL TABS
  #vertical_tabs: ^0.1.4 #using my version

  #STRING PROCESS
  diacritic: ^0.1.1
  
  #PATH PROVIDER
  path_provider: ^1.3.0
  
  #LAUNCH URL
  url_launcher: ^5.1.3

  #SLIDER
  flutter_xlider: ^2.5.2
  intl: ^0.15.8 #so it works with xlider

  #SETTINGS
  shared_preferences: ^0.5.3+4

  #THEME
  provider: ^2.0.1

  #STICKY HEADERS 
  flutter_sticky_header: ^0.4.0 

  #INDICATOR
  flutter_spinkit: ^4.0.0 #not used
  loading_indicator: ^1.1.0 #not used
  progress_indicators: ^0.1.4

  #VIBRATION
  vibration: ^1.2.1

  #LOADING
  liquid_progress_indicator: ^0.3.2

  #TESTING
  random_string: ^1.1.0

  #PICKER
  flutter_picker: ^1.0.15

  #SCROLL TO TOP
  scroll_to_index: ^1.0.2

  #TOAST (new contact warning)
  fluttertoast: ^3.1.0

  #ICONS
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0

  #TRANSITIONS
  page_transition: ^1.1.4

flutter_native_splash:
  image: assets/splash/splash.png
  color: "000000"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  #Required but not used if adaptive icons are supported
  image_path: "assets/launcher/icon2.png"
  adaptive_icon_foreground: "assets/launcher/icon2.png"
  adaptive_icon_background: "#000000"

dev_dependencies:
  flutter_test:
    sdk: flutter

  #SPLASH SCREEN
  flutter_native_splash: ^0.1.7+2

  #LAUNCHER
  flutter_launcher_icons: ^0.7.2+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/splash/splash.png
   - assets/gifs/breathMod.gif
   - assets/gifs/breathModBright.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
